.github/issue_template.md
I have added an `issue_template.md` file within the `.github` directory in the root, which has the structure of what we want our issues to look like. This format has been agreed on by all team members.
Closes #1
N/A
=> Adding the issue template.

CONTRIBUTING.md
I have added a contributing.md file within the root directory, which has the contributing guidelines that people can refer to. This format has been agreed on by all team members during a team meeting. Edit : Closes issue #4 
N/A
[ ] My code follows the style guidelines of this project
[ ] I have performed a self-review of my own code
[ ] I have commented my code, particularly in hard-to-understand areas
[ ] I have made corresponding changes to the documentation
[ ] My changes generate no new warnings
[ ] I have added tests that prove my fix is effective or that my feature works
[ ] New and existing unit tests pass locally with my changes
[ ] Any dependent changes have been merged and published in downstream modules
[ ] I have checked my code and corrected …
=> Docs: contributing guidelines

CODE_OF_CONDUCT.md
I have added a CODE_OF_CONDUCT.md file to the root directory. The format and contents was agreed on by team members during a team meeting. The code of conduct is completed. Some finer details regarding contributors/members of the 'community' can be updated once a team name etc. has been finalized. 
N/A
N/A
=> Docs: Add Code of Conduct Frontend

.eslintrc.json
*Please include a summary of the change and which issue number is fixed (e.g. Fixes #1). Please also include relevant motivation and context.*
The eslint config uses a deprecated prettier config.
Fixes: #36 
*Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.*
Ran locally to check if eslint works
=> Fix eslint config for prettier-react.

src/components/CourseCard/CourseCard.jsx, src/components/CourseCard/CourseCard.module.css, src/components/CourseCard/_tests_/CourseCard.test.jsx
Created a clickable Course card component and a corresponding test
Tested with react test. It test if the props are rendered and if the card changed correspondingly when its clicked
*Provide screenshots of what has been implemented. Leave blank if not applicable*
=> Course card component

src/components/CourseCard/_tests_/CourseCard.test.jsx
*Please include a summary of the change and which issue number is fixed (e.g. Fixes #1). Please also include relevant motivation and context.*
This fix the issue #56. The cause of the bug is the grid structured of the component changed and the number of student and buddy is no longer been put into the same Typography tag. Whereas the test was assuming it was still in the same Typography tag. The issue is fixed by removing the word "Member" and "Buddies" from the related test. 
*Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.*
npm test passed
*Provide screenshots of what has been implemented. Leave blank if not applicable*
=> fix: fixed the test for Course Card Component

src/context/serviceWorkerContext.jsx, src/serviceWorkerRegistration.js
Added no console warning to Pwa files.
I deployed a build on netlify and used the LightHouse tool in google developer tool to check the app is pwa. The url is [https://test701.netlify.app/](https://test701.netlify.app/).
=> add no console warning to Pwa files

src/Util/TimeFormater.js, src/components/ChatList/ChatList.jsx, src/components/ChatList/ChatList.module.css, src/components/ChatList/ChatListItem.jsx, src/components/ChatList/ChatListItem.module.css, src/components/ChatList/__tests__/ChatListItem.test.jsx, src/components/ChatList/__tests__/__snapshots__/ChatListItem.test.jsx.snap, src/components/ProfileBadge/ProfileBadge.jsx
Created a ChatListItem and ChatList components as in the [Issue 26](https://github.com/SE701-T1/frontend/issues/26)
Created react tests checking whether the component renders and can be selected and deselected
=> Chat list component

src/components/Loading/Loading.module.css, src/components/Loading/LoadingComponent.jsx, src/components/Loading/__tests__/LoadingComponent.test.jsx
Addition of loading component and the unit test
Fixes issue no. 31, creating the loading component. Will be able to be used as an overlay component for when loading is occurring. May require some changes once actually being implemented in the future, as it is currently difficult to test with no additional setup (currently sets up the basics).
Fixes #31 
Unit test has been written to verify it loading.
=> Created loading component and related file

src/api/CommunicationAPI.js, src/api/PairingAPI.js, src/api/TimetableAPI.js, src/api/UserAPI.js
This PR adds API stubs for communication, pairing, timetable and user, based off the backend. These new functions can now be called in different parts of the app and will return mock data.
This fixes #74 
Called the functions in parts of the app to see that the correct mock data is getting returned.
N/A
=> Added API stubs

src/components/ChatHeader/ChatHeader.jsx, src/components/ChatHeader/ChatHeader.module.css, src/components/ChatHeader/__tests__/ChatHeader.test.jsx, src/components/ChatHeader/__tests__/__snapshots__/ChatHeader.test.jsx.snap, src/components/ChatHeader/index.js
Implement the chatHeader component using the profile badge component. Followed design on Figma.
Closes #71 
Simple snapshot tests and react tests to see if the component is correctly rendered and expected text appear.
*Provide screenshots of what has been implemented. Leave blank if not applicable*
[Updated]
Buddy is online:
Buddy is offline:
=> ChatHeader Component

src/pages/Routes/AuthRoutes.jsx, src/pages/Routes/__tests__/AuthRoutes.test.jsx
The intent of this pull request is to implement the React route middleware (as discussed in Issue #16). The implementation, however, is different to the way it was proposed earlier.
Rather than extending the `Route` class provided by React, we have created this component that accepts `children`. If the user is logged in, the component will render the `children` - otherwise, the user will be redirected to the `root `/` which is the Login page. This component will find out whether the user is logged in or not, using the global authentication context implemented in #61.
Closes #16 
Some basic unit tests have been added for this component. The following test cases are covered:
* The `children` components are rendered if the context signals that the user is logged in.
N/A
*(Leave blank if not …
=> Feature: React route middleware

CONTRIBUTING.md
Resolves issue #98 . The changes fix spelling, grammar, readability and remove placeholders.
N/A
N/A
=> Edit contributing guidelines

.github/workflows/react_testing.yml
This PR fixes the CI issue present in #106 
This was done by breaking the node setup and caching into two separate steps, and also giving a path value.
Tested the CI using a pull request.
N/A
N/A
=> Fix CI issue

src/components/Carousel/__tests__/Carousel.test.js
This PR fixes the import error present in #107 
Ran npm test and verified that all the tests are now passing
N/A
=> Import error fix

src/api/PairingAPI.js, src/api/UserAPI.js
Removed the convertBuddy function from PairingAPI and UserAPI as buddy count has now been added in the backend
Fixes #111 
N/A
N/A
=> Removed convertBuddy function

src/pages/Settings/__tests__/Settings.test.jsx, src/pages/Settings/__tests__/__snapshots__/Settings.test.jsx.snap
The test bug specified in #125 has been resolved here by adding a basic snapshot test for the `Settings` component.
Closes #125 
N/A
N/A
=> Bug: Fixed tests in Settings page

CONTRIBUTING.md
Fixes #123  . Adds link to issue label wiki
N/A
N/A
=> add link to wiki

README.md
React's default `README.md` file has been modified with information tailored to our project. This includes instructions on how to run/test the project and setup the linting environment on VSCode.
Closes #22
N/A
N/A
=> Documentation: Update default README.md

src/components/ChatBuddyDetail/ChatBuddyDetail.jsx, src/components/ChatInput/ChatInput.jsx, src/components/ChatInput/__tests__/__snapshots__/ChatInput.test.jsx.snap, src/components/ChatList/ChatList.jsx, src/components/ChatList/ChatListItem.jsx, src/components/UserSearch/UserSearch.jsx, src/pages/Chat/Chat.jsx
Refactor and Fix up glitches picked up from Demo
Fixes #131
- Fix search focus is lost after useState
- Implement similar courses on chat detail page
- Minor UI fixes for flow
- Add comments to components that is missing comments
*Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.*
Tested for the demo
*Provide screenshots of what has been implemented. Leave blank if not applicable*
=> Fix up minor UI glitches for the Demo
